### ISSUE TITLE
Unable to launch streamlink / media player 

### ISSUE THREAD

**Issue by ThBa** [flathub/com.chatterino.chatterino#1]
**Describe your issue**
I don't this it's a Chatterino issue, but more linked to flatpak packaging. 

While using flatpak version of Chatterino, I'm unable to launch a stream with streamlink. 
- It doesn't work if I install it with host pip ; streamlink custom path `/home/thba/.local/bin`
```bash
Traceback (most recent call last):
  File "/home/thba/.local/bin/streamlink", line 5, in <module>
    from streamlink_cli.main import main
ModuleNotFoundError: No module named 'streamlink_cli'
```
- It doesn't work if I install it with appimage ; streamlink custom path `/home/thba/.local/bin`
```bash
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

I managed to make it work with an exploded appimage (using `--appimage-extract`) and by modifying in streamlink binary the interpreter by the python provided in the exploded appimage. But then I'm having trouble with launching media players; I tried with VLC and MPV.

From my understanding, the issue with media players is because it's looking for libraries (eg: libvlc.so) that can't be found in flatpak's library directories.
```bash
ldd /run/host/usr/bin/vlc
	linux-vdso.so.1 (0x00007ffd98f67000)
	libvlc.so.5 => not found
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f07424ae000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007f07424a8000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f07422dd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f07424eb000)
```

I'm not very confortable with flatpak, and while I tried to tweak it a little I don't know how to add libraries or if it's even possible.

Also, I don't have any issues if I'm running a same-ish config with Chatterino appimage.

**OS and Chatterino Version**
   Ubuntu 20.04, flatpak Chatterino v2.3.2

**Comment by ilyazzz** [comment]
I'll look into it, it's possible to ship streamlink with the flatpak, but I'm not 100% sure how streamlink itself would go about calling an external player.

**Comment by ilyazzz** [comment]
@ThBa I've managed to include streamlink with the flatpak, but it seems like streamlink calls external players as shell commands, which doesn't work from within the sandbox. The possible solutions for this are:
- Make chatterino call streamlink on the host with `flatpak-spawn`. This would require streamlink to be installed on the host system (like it is in your case), but then it can use whatever player you have installed like you'd expect it to.
- Include something like mpv in the flatpak. This would make the application bigger (though not substantially, as mpv is pretty light), and it would also make mpv the only option, but it would work out of the box without needing anything extra installed. This is also probably the easiest option to implement.
- Make streamlink running from inside the sandbox call external players with `flatpak-spawn` (likely won't be doing this).

**Comment by ThBa** [comment]
Imho you should keep streamlink outside of the flatpak, so the first solution should be the better one. But of course while I think it's the better option it's also not possible! 

- I first tried while loading a shell in the flatpak and typing the command: `flatpak-spawn --host /home/thba/.local/bin/streamlink --player /usr/bin/mpv twitch.tv/my_fav_streamer --default-stream best,worst` and everything worked fine.
Then I tried through Chatterino. But you can only specify a custom path toward `streamlink` executable, it's not possible to change the name of the executable launched to `flatpak-spawn`. A workaround could be to add inside the flatpak a symlink from `/usr/bin/streamlink` to `/usr/bin/flatpak-spawn` but again I don't think this is the correct solution.

- Including a media player in the flapak is not an option I think. At least not in my opinion.

- Launching the player with `flatpak-spawn` is working. You need to tweak the launch options in Chatterino's additional options to `--player flatpak-spawn --player-args "--host /usr/bin/mpv"`. But then you are forced to use the streamlink included in the flatpak.

So I guess that if I want to use the first option I should ask Chatterino team if it's possible to specify the whole path to streamlink binary in it's additional options?

**Comment by ilyazzz** [comment]
It's possible to make Chatterino check if it's running as a flatpak, and if it is call streamlink with `flatpak-spawn`. Though I'd still prefer to include streamlink with the flatpak so it works out of the box, it would probably be slightly harder to insert `flatpak-spawn` into the streamlink arguments than to just call streamlink on the host.

Implementing the first option seems trivial, it's possible to check if it's running as a flatpak by checking if the `FLATPAK_ID` environment variable is present, in which case it should wrap streamlink with `flatpak-spawn --host`. Unfortunately I'm not very familiar with C++ so I couldn't get it to work, I'll see if I can get any Chatterino devs to assist with this.

**Comment by ilyazzz** [comment]
@ThBa sorry for the big delay, I've pushed a fix (for now it's a patch) and it should be available on flathub once the CI is done.

**Comment by ThBa** [comment]
Np for the delay you did it when you could, plus I had a workaround in the meantime. 
I guess by today it's deployed, and everthing is working perfectly, I can even use Streamlink through appimage! 

Thanks for your help, I'm closing this issue
