### ISSUE TITLE
Chatterino uses xwayland with current configuration

### ISSUE THREAD

**Issue by Keelhauled** [flathub/com.chatterino.chatterino#110]
By removing the env variable QT_QPA_PLATFORM=xcb qt seems to be able to auto detect wayland or x11. Is there a reason for this variable or can it be removed?

**Comment by ilya-zlobintsev** [comment]
Yes, this behaviour is intentional as Chatterino has several bugs which make the user experience not great when running under native wayland:
https://github.com/Chatterino/chatterino2/issues/1647
https://github.com/Chatterino/chatterino2/issues/3501
