### ISSUE TITLE
chatterino 2.4.0

### ISSUE THREAD

**Issue by alok0** [flathub/com.chatterino.chatterino#6]
2.4.0 has been released.

https://github.com/Chatterino/chatterino2/releases/tag/v2.4.0

**Comment by Cyborgeagle** [comment]
> 2.4.0 has been released.
> 
> https://github.com/Chatterino/chatterino2/releases/tag/v2.4.0

Please update the Flatpak.

**Comment by ilya-zlobintsev** [comment]
I've pushed the new version, it should be up on flathub soon.
